language: php

php: 7.3

services:
  - mysql

env:
  global:
    - WP_DB_USER=wp
    - WP_DB_PASS=password
    - WP_DB_NAME=wp_tests

before_install: composer validate --strict

install: composer install

before_script:
  - mysql -u root -e "GRANT ALL PRIVILEGES ON $WP_DB_NAME.* TO $WP_DB_USER IDENTIFIED BY '$WP_DB_PASS';"
  - mysql -u root -e "CREATE DATABASE $WP_DB_NAME;"

script: composer test
